version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000" # Используйте переменную PORT из .env
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME} 
      DB_PORT: ${DB_PORT} 
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME} 
    ports:
      - "3306:3306"
